services:
  vulcanosBakeryShop:
    image: mongo:5.0.0
    container_name: vulcanosDB
    volumes:
      - ./mongo/:/data/db/
    ports:
      - 27017:27017
  vulcanosBackend:
    image: vulcanos-backend-image
    container_name: vulcanos-backend-container
    ports:
      - 8000:8000
  vulcanosFrontend:
    image: vulcanos-frontend-image
    container_name: vulcanos-frontend-container
    ports:
      - 3000:3000
